-- USERS / ROLES
CREATE ROLE db_owner NOLOGIN;

CREATE ROLE db_admin LOGIN CREATEDB PASSWORD 'PASSWORD';
GRANT db_owner TO db_admin;

CREATE ROLE app LOGIN PASSWORD 'PASSWORD';

-- DATABASE
CREATE DATABASE tehnicni_pregledi
    OWNER db_owner
    TEMPLATE template0
    ENCODING 'UTF8'
    LOCALE_PROVIDER icu
    ICU_LOCALE 'sl-SI';

\connect tehnicni_pregledi

CREATE SCHEMA tehnicni AUTHORIZATION db_owner;

-- Enable pgcrypto for UUID
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Disable public schema
REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;

-- PERMISSIONS
GRANT USAGE, CREATE ON SCHEMA tehnicni TO db_admin;
GRANT ALL ON SCHEMA tehnicni TO db_admin;

GRANT USAGE ON SCHEMA tehnicni TO app;
REVOKE CREATE ON SCHEMA tehnicni FROM app;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA tehnicni TO app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA tehnicni TO app;

ALTER DEFAULT PRIVILEGES FOR ROLE db_admin IN SCHEMA tehnicni
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app;

ALTER DEFAULT PRIVILEGES FOR ROLE db_admin IN SCHEMA tehnicni
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO app;
